version: '3'
services:
  ## Users service postgres database.
  postgres-users:
    container_name: postgres-users
    image: postgres
    environment:
      POSTGRES_DB: quizlydb
      POSTGRES_USER: quizly
      POSTGRES_PASSWORD: quizly
      PGDATA: /data/postgres
    volumes:
      - /tmp/postgres-users:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    restart: unless-stopped

