pipeline {
    agent any
    stages {
        stage('chekout') {
            steps {
                // generated by 
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'Pat_jenkins', url: 'https://github.com/rebirth2001/QUIZLY.git']])
                
            }
        }
    
 stage('Build and Test Microservices') {
            steps {
                script {
                    // Spécifiez le dossier du microservice
                    def microserviceFolder = 'eureka'  // Remplacez par le nom réel de votre dossier

                    // Exécutez le Jenkinsfile du microservice
                    echo "Building and testing ${microserviceFolder}"
                    build job: "${microserviceFolder}/Jenkinsfile", wait: true
                }
            }
        }

    }
}
