on:
  push:
    branches: [main]
    paths:
      - 'back/app/**'
  pull_request:
    branches: [main]
    paths:
      - 'back/app/**'

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Setup Java environment
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build project and download dependencies
      - name: Build with Maven
        run: mvn -B package --file back/app/pom.xml

      # Run Snyk to check for vulnerabilities in the Spring Boot project
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_SECRET }}
        with:
          args: --file=back/app/pom.xml
