name: ZAP CI Scan 
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze with PostgreSQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PostgreSQL Client
        run: sudo apt-get install postgresql-client

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
  scans:
    run-on: ubuntu-latest
    name: ZAP API Scan 
    steps:
      - name: Checkout code
        uses: action/checkout@v2
      - name: log current directory
        run: echo ${pwd}
      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly
      - name: Run ZAP API Scan 
        run: |
          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t openapi.json -f openapi -c api-scan.conf
  